### ISSUE TITLE
Ability to wait for a new rancher2 catalog to be ready

### ISSUE THREAD

**Issue by iTaybb** [rancher/terraform-provider-rancher2#201] opened 2019-12-04 22:07 UTC
When I'm loading a new `rancher2_catalog` resource, it takes half a minute for the charts to load.
If I'm trying to create an app from it afterwards - it fails with error 500 (since the chart is not ready yet).

Example code that will fail if both resources are created in the same run:

```
resource "rancher2_catalog" "helm" {
  provider = "rancher2.admin"
  name = "helm"
  url = "https://kubernetes-charts.storage.googleapis.com/"
}

data "rancher2_project" "system" {
  provider = "rancher2.admin"
  cluster_id = rancher2_cluster_sync.aws-primary.id
  name       = "System"
}

resource "rancher2_app" "nfs-client-provisioner" {
  provider = "rancher2.admin"
  catalog_name = rancher2_catalog.helm.name
  name = "nfs-client-provisioner"
  description = "nfs-client-provisioner"
  project_id = data.rancher2_project.system.id
  template_name = "nfs-client-provisioner"
  template_version = "1.2.8"
  target_namespace = "kube-system"
  answers = {
    "nfs.mountOptions"          = "{'vers=4.1','noatime'}"
    "nfs.path"                  ="/"
    "nfs.server"                = aws_efs_file_system.primary.dns_name
    "storageClass.defaultClass" = true
  }
}
```

A resource similar to `rancher2_cluster_sync` for catalogs could be cool. Or even better, have a `wait-until-ready` parameter inside the `rancher2_catalog` resource creation.

**Comment by rawmind0** [comment] 2019-12-05 19:07
Hi @iTaybb , `rancher2_catalog` resource is waiting until `active` state on creation. The problem is that once catalog is created it gets `active` state before the refresh action. We could add a `refresh` bool argument to wait for a refresh action once it's created. Do you think would be useful to also add refresh on read (`terraform apply`)??

**Comment by iTaybb** [comment] 2019-12-06 10:57
You mean, a `refresh` bool argument to wait for a refresh action to be *done*, yes?

Regarding the refresh on read - I think yes.

**Comment by rawmind0** [comment] 2019-12-06 14:45
Submitted PR #203 to fix issue

**Comment by rawmind0** [comment] 2019-12-17 06:37
PR merged into master. Please, reopen issue if needed.

**Closed as completed by rawmind0** 2019-12-17 06:37 UTC

**Comment by atsai1220** [comment] 2020-05-26 18:30
Running into this exact issue right now. Adding `depends_on` to `rancher2_app` resource and `refresh = "true"` to `rancher2_catalog` resolves the issue for me. Sharing for anyone that runs into this.

My scenario: The App is found and installs correctly if I apply Terraform the second time (when the chart is fully instantiated and without `depends_on` but with `refresh = "true"`). 

The Chart that I am pointing to is large so that may be an issue. Below is my `.tf` file. Removing `depends_on` will cause the app to not be found the first run. 

I imagine it is because the Chart is quite large. There isn't an issue when pulling from smaller Chart.

```
# Create a new cluster catalog entry for Velero
resource "rancher2_catalog" "helm" {
    provider = rancher2.admin
    name = "official-helm"
    url = "https://kubernetes-charts.storage.googleapis.com/"
    scope = "cluster"
    cluster_id = var.target_cluster_id
    version = "helm_v2"
    refresh = "true"
}

# Find System project id
data "rancher2_project" "system" {
  provider = rancher2.admin
  cluster_id = var.target_cluster_id
  name = "System"
}

# Create namespace
resource "rancher2_namespace" "nfs_provisioner" {
  provider = rancher2.admin
  name = "nfs-server-provisioner"
  project_id = data.rancher2_project.system.id
}

# Deploy nfs-provisioner as App
resource "rancher2_app" "nfs_provisioner" {
  provider = rancher2.admin
  catalog_name = "${var.target_cluster_id}:official-helm"
  name = "nfs-server-provisioner"
  project_id = data.rancher2_project.system.id
  template_name = "nfs-server-provisioner"
  target_namespace = "nfs-server-provisioner"
  values_yaml = var.helm_answers

  depends_on = [
    rancher2_catalog.helm,
  ]
}
```
