### ISSUE TITLE
Project Monitoring doesnt upgrade

### ISSUE THREAD

**Issue by Arola1982** [rancher/terraform-provider-rancher2#407] opened 2020-08-05 10:28 UTC
When changing versions of the monitoring terraform shows it modifying the project resource, but in actual fact the resource in rancher stays on the current version.

Shouldnt this trigger a redeploy of the later version?

**Comment by armsnyder** [comment] 2020-08-05 17:48
Possible duplicate of #376?

**Comment by rawmind0** [comment] 2020-08-10 10:23
PR #409 is merged to master and should address this issue. Please reopen it if needed.

**Closed as completed by rawmind0** 2020-08-10 10:23 UTC
