### ISSUE TITLE
Creating alert after cluster_sync(wait for monitoring) gives us error.

### ISSUE THREAD

**Issue by julienym** [rancher/terraform-provider-rancher2#479] opened 2020-10-20 12:56 UTC
Rancher 2.4.5
RKE Cluster: v1.16.15
Monitoring version: 0.1.1

Hi we are having the error msg, when trying to create rancher2_cluster_alert_rule.
We do use the cluster_sync+wait for monitoring...
---
Error: Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [baseType=error, code=ServerError, message=if you want to use metric alert, need to enable monitoring for cluster c-v862q] from [https://rancher-dev.XXX.XXX.XXX/v3/clusteralertrules]
---

The weird thing is that it's not happening all the time - but too often.

_Originally posted by @julienym in https://github.com/rancher/terraform-provider-rancher2/issues/316#issuecomment-712823062_

gz#12924

**Comment by angeloudy** [comment] 2020-10-22 23:04
I am having the same issue and it happens every time. I reckon even with `wait_monitoring`, it still not waiting long enough because every time if I ran `terraform apply` again, it works

**Comment by rawmind0** [comment] 2020-10-26 12:58
could you please provide tf file to reproduce the issue??

**Comment by rawmind0** [comment] 2020-10-27 23:47
PR #487 add a fix for this issue.

**Closed as completed** 2020-10-29 17:11 UTC
