### ISSUE TITLE
[BUG] Changes not detected in project resource

### ISSUE THREAD

**Issue by matttrach** [rancher/terraform-provider-rancher2#1373] opened 2024-07-23 22:04 UTC
### Rancher Server Setup
- Rancher version:
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

### Information about the Cluster
- Kubernetes version:
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

### User Information
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:
unknown?

### Provider Information
- What is the version of the Rancher v2 Terraform Provider in use? terraform provider rancher2 (4.2.0)
- What is the version of Terraform in use? terraform version 1.5.7

### Describe the bug
Terraform is not detecting a change in the project resource when labels are updated.

### To Reproduce
1. Create project with labels and make sure it completes.
2. Update project labels
3. Run terraform plan

### Actual Result
Terraform is not detecting a change in the resource.

### Expected Result
Terraform should see a difference between the config and reality, and should show a planned change to update the resource.
Then when running apply we should see the update alter the labels without destroying the object.

### Additional context

We are using the terraform provider rancher2 (4.2.0) to manage the rancher projects with the resource rancher2_project: while during the creation of the project the resource take care of set up also the  labels for the  project k8s resource, if we modify the labels for the project the resource rancher2_project don't update the labels.  
In the following a snippet with the interested code:
```
resource "rancher2_project" "main" {
  for_each = jsondecode(var.clusters_config == "" ? "{}" : var.clusters_config)

  name       = var.project_name
  cluster_id = each.value.cluster_id

  resource_quota {
    project_limit {
      limits_cpu       = can(each.value.limits_cpu) ? each.value.limits_cpu : null
      limits_memory    = can(each.value.limits_memory) ? each.value.limits_memory : null
      requests_storage = can(each.value.requests_storage) ? each.value.requests_storage : null
    }

    namespace_default_limit {
      limits_cpu    = "0m"
      limits_memory = "0Mi"
    }
  }

  labels = {
    "group"          = var.project_name
    "owner"          = var.owner
    "department"     = var.department
    "stakeholder"    = var.stakeholder
    "admin_contacts" = var.admin_contacts
  }
}
```

**Comment by matttrach** [comment] 2024-07-23 22:09
created from messages with @ncuralli

**Comment by maxsokolovsky** [comment] 2024-07-30 19:11
I haven't been able to reproduce this. I tried with a map of labels specified in-line and with references to a variable for a label's value. Used the same version of the provider (4.2.0) and Terraform itself (1.5.7).

**Comment by ncuralli** [comment] 2024-07-30 19:23
posting execution log
[tag-terraform-plan.txt](https://github.com/user-attachments/files/16432507/tag-terraform-plan.txt)

**Comment by ncuralli** [comment] 2024-08-08 05:54
We found a bug on how we fill the labels dictionary. please close this bug because there is no bug on the the provider code

**Closed as completed** 2024-08-13 20:39 UTC
Labels: pr-impact/patch
