### ISSUE TITLE
rancher2_app_v2 fails to install latest rancher monitoring, logging, backups and longhorn

### ISSUE THREAD

**Issue by abhi1693** [rancher/terraform-provider-rancher2#739] opened 2021-09-03 20:56 UTC
@rawmind0 
For a newer release that uses the format `100.0.0+up1.0.0`, the `chart_version` should be provided with the value as `100.0.0%2B1.0.0` otherwise the operation fails with 500 when installing, however, it works well on upgrade using `100.0.0+up1.0.0`

**Comment by mouellet** [comment] 2021-09-08 14:50
I can confirm this using Ranche v2.6. Here's the error:
> Error: Timeout getting chart info rancher-monitoring:100.0.0+up16.6.0 from catalog v2 rancher-charts: Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [code=ServerError, message=improper constraint: 100.0.0 up16.6.0] from [https://rancher.k3d.localhost/v1/catalog.cattle.io.clusterrepos/rancher-charts?link=info&chartName=rancher-monitoring&version=100.0.0+up16.6.0]

The `+` sign seems to be escaped...

**Comment by jmatsushita** [comment] 2021-09-15 09:41
I confirm that I have this problem too. It means changing to `%2B` when an operation requires a replace, and changing back to `+` when it can update in place... Needless to say this is inconvenient in pipelines :)

EDIT: Unfortunately there are cases where several API calls are made in case even of update in place, in which case neither `%2B` not `+` allows to avoid the `improper constraint` error.

**Comment by jmatsushita** [comment] 2021-09-15 10:49
@rawmind0 Would you accept a PR for this bug?

**Comment by rawmind0** [comment] 2021-09-15 11:37
@jmatsushita , sure, more than happy to accept a PR for this. Thanks in advance

**Comment by rawmind0** [comment] 2021-09-17 11:45
@jmatsushita , submitted PR https://github.com/rancher/terraform-provider-rancher2/pull/746 to fix the issue

**Comment by rawmind0** [comment] 2021-09-17 14:38
PR #746  alredy merged. the fix will be available at next tfp release v1.20.0

**Closed as completed by rawmind0** 2021-09-17 14:38 UTC
