### ISSUE TITLE
rancher catalog creation times out, cannot destroy to recreate

### ISSUE THREAD

**Issue by kevinpgrant** [rancher/terraform-provider-rancher2#151] opened 2019-10-08 08:39 UTC
Terraform provider does not seem to recognise the creation of a catalog object in Rancher, when configured with an incorrect setting (eg wrong password, leading to a 401 error loading the catalog contents)

Due to the error, terraform thinks that creation was unsuccessful and appears not to add it to state. This means that fixing the error in code and reapplying results in an object already exists kind of message.

The other approach of `terraform destroy -target thing` says delete successful, 0 resources removed, and again - attempting to deploy results in object already exists message. It is necessary to manually intervene in the UI to remove the failed catalog before reapplying

```
# Create a new rancher2 Cluster Catalog
resource "rancher2_catalog" "cluster_sit" {
  branch     = "develop"
  cluster_id = "my_id"
  kind       = "helm"
  name       = "cluster"
  password   = var.gitlab_pw
  scope      = "cluster"
  url        = "https://gitlab...../rancher-charts.git"
  username   = var.gitlab_user
}
```

Expected result: able to update, delete or create a catalog via terraform without having to manually remove between steps

**Comment by kevinpgrant** [comment] 2019-10-08 09:09
For the benefit of anyone else struggling with this (who doesnt have sufficient admin privileges to remove via the UI) it is possible to import the "broken" object via TF and then destroy:

```
$ terraform import module.rancher.rancher2_catalog.cluster_sit  cluster.c-jp75b:catalog-cluster
module.rancher.rancher2_catalog.cluster_sit: Importing from ID "cluster.c-jp75b:catalog-cluster"...
module.rancher.rancher2_catalog.cluster_sit: Import prepared!
  Prepared rancher2_catalog for import
module.rancher.rancher2_catalog.cluster_sit: Refreshing state... [id=c-jp75b:catalog-cluster]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
```

and remove:
```
$ terraform destroy -target module.rancher.rancher2_catalog.cluster_sit

Terraform will perform the following actions:
<snip>
Plan: 0 to add, 0 to change, 1 to destroy.
<snip>
Destroy complete! Resources: 1 destroyed.
```

**Comment by rawmind0** [comment] 2019-10-08 10:25
@kevinpgrant , by default, terraform doesn't undo anything if any step fails. For create catalogs, tf provider is doing basically 2 steps, creating the catalog and waiting for its `active` state. In your case, i guess that it's failing in the wait step. We can add a patch that removes catalog if wait is failing at creation.

Thanks for adding import workaround steps.

**Comment by kevinpgrant** [comment] 2019-10-08 11:54
@rawmind0 yes, you seem to sum it up perfectly. Without looking at the code closely, my guess is the wait step is checking the API for a value such as:

```
"state": "active",
"transitioning": "no",
"transitioningMessage": "",
```

Whereas it could just check for createdTS instead, perhaps?
```
"created": "2019-10-08T10:46:27Z",
"createdTS": 1570531587000,
```

I have also noticed that once created successfully, every subsequent plan wants to update the "password", thinking it has changed when it hasn't. Will attempt to use a `lifecycle ... ignore_changes` setting on that field to quiet it for now.

Thanks for taking a look at this issue :)

**Comment by rawmind0** [comment] 2019-10-08 11:59
The problem is that catalog was created but it is not getting active state. That's why you are getting timeout. What we can do is to remove it, if the wait doesn't finish successfully, what dp you think??

BTW, thanks for reporting the password issue, i'll take a look to fix both issues.

**Comment by kevinpgrant** [comment] 2019-10-08 12:17
is it possible to add multiple states for Target? same as you can have multiple values for Pending perhaps? https://github.com/hashicorp/terraform/blob/1ee851f2564af86404110d1c5be5b34d36ddf323/helper/resource/state.go#L27

**Comment by rawmind0** [comment] 2019-10-08 12:24
Yeah, it's possible. But it would silently fails if the catalog is not getting active. The catalog will be created but may be it's not active. I'd prefer control state and get an error if the state is not active, removing catalog if needed.

**Comment by kevinpgrant** [comment] 2019-10-08 12:24
Ah, ignore that last comment - wanted to add "refreshed" to Terget, because that is the state it gets stuck in, but it doesn't make sense to have that value for both pending and target. 

I guess just removing the failed catalog if it doesn't succeed is cleaner.

**Comment by rawmind0** [comment] 2019-10-10 11:38
Submitted PR to address this issue.

**Comment by rawmind0** [comment] 2019-10-11 17:55
PR merged. Please, reopen issue if needed

**Closed as completed by rawmind0** 2019-10-11 17:55 UTC
