### ISSUE TITLE
Intermittent errors creating v2 app (rancher2_app_v2) during appV2OperationWait

### ISSUE THREAD

**Issue by brettmorien** [rancher/terraform-provider-rancher2#586] opened 2021-02-17 19:46 UTC
We are having issues where our cluster builds are failing when installing v2 apps. They install correctly, but during the appV2OperationWait, it immediately calls the Rancher API to get the resource information to inspect for transitioning state. For a brief period, that GetAppV2OperationByID API call may return a 500 error (which would succeed shortly later). This causes the wait operation to fail and abort the terraform.

This occurs intermittently. This is with the v1.11.0 version of the plugin.

```
Test 2021-02-17T18:13:24Z logger.go:66: module.<mymodule>.rancher2_app_v2.harbor: Still creating... [10s elapsed]
Test 2021-02-17T18:13:34Z logger.go:66: module.<mymodule>.rancher2_app_v2.harbor: Still creating... [20s elapsed]
Test 2021-02-17T18:13:44Z logger.go:66: module.<mymodule>.rancher2_app_v2.harbor: Still creating... [30s elapsed]
Test 2021-02-17T18:13:54Z logger.go:66: module.<mymodule>.rancher2_app_v2.harbor: Still creating... [40s elapsed]
Test 2021-02-17T18:13:54Z logger.go:66: 
Test 2021-02-17T18:13:54Z logger.go:66: Error: [ERROR] installing App V2: Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [dial tcp 127.0.0.1:6080: connect: connection refused] from [https://<clusterDomain>/k8s/clusters/c-82vcx/v1/catalog.cattle.io.operations/harbor-system/helm-operation-57jp8]
Test 2021-02-17T18:13:54Z logger.go:66: 
Test 2021-02-17T18:13:54Z logger.go:66:   on ../harbor.tf line 30, in resource "rancher2_app_v2" "harbor":
Test 2021-02-17T18:13:54Z logger.go:66:   30: resource "rancher2_app_v2" "harbor" {
```

``` terraform
resource "rancher2_catalog_v2" "harbor" {
  name       = "harbor"
  url        = "https://helm.goharbor.io/"
  cluster_id = rancher2_cluster_sync.this.cluster_id
}

resource "rancher2_app_v2" "harbor" {
  repo_name     = rancher2_catalog_v2.harbor.name
  chart_name    = "harbor"
  chart_version = "1.5.3"
  project_id    = rancher2_cluster_sync.this.system_project_id
  cluster_id    = rancher2_cluster_sync.this.cluster_id
  name          = "harbor-registry"
  namespace     = rancher2_namespace.harbor_system.name
  wait          = true
  values = yamlencode({...})
}
```

**Comment by armsnyder** [comment] 2021-02-17 20:58
Would it be reasonable to rewrite the `appV2OperationWait` function to use either [resource.Retry](https://www.terraform.io/docs/extend/resources/retries-and-customizable-timeouts.html#retry) or [resource.StateChangeConf](https://www.terraform.io/docs/extend/resources/retries-and-customizable-timeouts.html#statechangeconf), and to treat a 500 error as retriable?

I think this failure is common because the `appV2OperationWait` function calls the `GetAppV2OperationByID` API many times on a loop without backoff, increasing the likelihood of seeing a 500 error.

**Comment by armsnyder** [comment] 2021-02-18 00:12
Question for maintainers: Is there a reason this plugin does not retry _any_ API operation that results in a 500/502/503/504 HTTP status, or would that be a nice addition? Retries for all resources could be globally configured/disabled using a new `retry_timeout` provider config argument.

**Comment by rawmind0** [comment] 2021-02-19 13:20
@brettmorien , issue reproduced. Submitted PR https://github.com/rancher/terraform-provider-rancher2/pull/588 to fix it.

> Question for maintainers: Is there a reason this plugin does not retry any API operation that results in a 500/502/503/504 HTTP status, or would that be a nice addition? Retries for all resources could be globally configured/disabled using a new retry_timeout provider config argument.

@armsnyder , the reason is simple, opensource project, many requests/issues and not enough resources to do all stuffs in a row. For sure, this would be a nice addition, moreover now that these kind of issues are occurring. Contributions would be very welcomed. :)

**Comment by armsnyder** [comment] 2021-02-20 01:28
@rawmind0 Of course, I should have phrased that better as "are there technical reasons". 😄 

By the way I started working on adding retries throughout the codebase (https://github.com/armsnyder/terraform-provider-rancher2/commit/8aca65d04c1afa941234a20742e1e4cc236dcfe4), but there were hundreds of places needing to be changed, and it wasn't tractable for me to find/implement all of them. I think it would be better moved into the generated client.

**Comment by rawmind0** [comment] 2021-02-22 12:05
> By the way I started working on adding retries throughout the codebase (armsnyder@8aca65d), but there were hundreds of places needing to be changed, and it wasn't tractable for me to find/implement all of them. I think it would be better moved into the generated client.

Thanks @armsnyder . Yeah, agreed that retry should be implemented on client side. Let me invest some time on that and i'll back to you asap. In the meanwhile, i guess the submitted patch should be enough to make that work properly.

**Comment by brettmorien** [comment] 2021-02-23 20:12
Hi @rawmind0 

Are you considering cutting a release including this fix in the near future? We would love to increase the reliability in our CI system.

**Comment by rawmind0** [comment] 2021-02-25 17:11
Hi @brettmorien , yeah, we'll cut a new release next week, once rancher v2.5.6 is released.

**Comment by rawmind0** [comment] 2021-02-26 15:24
PR #588 is already merged. It will be included on next tfp release.

Please reopen issue if needed.

**Closed as completed by rawmind0** 2021-02-26 15:24 UTC
