### ISSUE TITLE
project, namespace, apps dependency cannot be detected

### ISSUE THREAD

**Issue by angeloudy** [rancher/terraform-provider-rancher2#366] opened 2020-06-10 00:33 UTC
Steps to reproduce:
1. create a project `project1` 
2. create a namespace `ns-1` in `project1`
3. create an app in namespace `ns-1`
all with rancher2 provider
Then delete project manually and ran `terraform apply`
Errors like the following will be thrown
```
Error: Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [baseType=error, code=ServerError, message=catalogTemplateVersion.management.cattle.io "cattle-global-data/neon-parent-chart-neon-development-0.0.40363" not found] from [https://rancher.xxx.cloud/v3/project/c-rqqbn:p-wr9zv/apps/p-wr9zv:xxx-dev?action=upgrade]
```

If I only delete the namespace manually, 
```
  on apps.tf line 19, in resource "rancher2_app" "qa":
  19:   target_namespace = rancher2_namespace.qa[count.index].name
    |----------------
    | count.index is 0
    | rancher2_namespace.qa is empty tuple

The given key does not identify an element in this collection value.

```

Here's my terraform template
```
data "rancher2_project" "quality" {
  cluster_id = data.rancher2_cluster.rancher_development.id
  name = "quality"
}
resource "rancher2_namespace" "qa" {
  count = length(var.qa-stacks)
  name = "${var.qa-stacks[count.index]["customer"]}-qa"
  description = "${var.qa-stacks[count.index]["customer"]} namespace"
  project_id = data.rancher2_project.quality.id
}

resource "rancher2_app" "qa" {
  depends_on = [rancher2_namespace.qa]
  count = length(var.qa-stacks)
  catalog_name = data.rancher2_catalog.parent-chart.name
  name = "${var.qa-stacks[count.index]["customer"]}-qa"
  project_id = data.rancher2_project.quality.id
  target_namespace = rancher2_namespace.qa[count.index].name
  template_name = "neon-quality"
  template_version = var.qa-stacks[count.index]["version"]
  values_yaml = filebase64("files/development-values.yaml")
  answers = {
    "global.customer" = var.qa-stacks[count.index]["customer"]
    "tags.${var.qa-stacks[count.index]["tags"]}" = "true"
  }
}
```

**Comment by rawmind0** [comment] 2020-08-05 15:44
> Steps to reproduce:
>1. create a project `project1` 
>2. create a namespace `ns-1` in `project1`
>3. create an app in namespace `ns-1`
>all with rancher2 provider
>Then delete project manually and ran `terraform apply`
>Errors like the following will be thrown
>```
> Error: Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [baseType=error, code=ServerError, message=catalogTemplateVersion.management.cattle.io "cattle-global-data/neon-parent-chart-neon-development-0.0.40363" not found] from [https://rancher.xxx.cloud/v3/project/c-rqqbn:p-wr9zv/apps/p-wr9zv:xxx-dev?action=upgrade]
>```

@angeloudy  , this part of the issue has been reproduced. PR #408 should address it.

>If I only delete the namespace manually, 
>```
> on apps.tf line 19, in resource "rancher2_app" "qa":
> 19:   target_namespace = rancher2_namespace.qa[count.index].name
>    |----------------
>    | count.index is 0
>    | rancher2_namespace.qa is empty tuple
>
>The given key does not identify an element in this collection value.
>
>```

This part of the issue is not related with the provider. The issue is related to terraform and the way that count is being used on `target_namespace`. As error message shows, if you delete the namespace manually, then the `rancher2_namespace.qa` count is 0 on terraform, [using-expressions-in-count](https://www.terraform.io/docs/configuration/resources.html#using-expressions-in-count). Updating `target_namespace = ${var.qa-stacks[count.index]["customer"]}-qa` should address your issue. May be here, the use of `for_each` is preferred instead of `count`, take a look to [when-to-use-for_each-instead-of-count](https://www.terraform.io/docs/configuration/resources.html#when-to-use-for_each-instead-of-count). 

I've also noticed that there was a typo on the rancher2_app documentation. `target_namespace` argument should point to namespace id nor name (also fixed on mentioned PR).

**Comment by rawmind0** [comment] 2020-08-05 17:37
@angeloudy  PR is merged to master. Please, reopen issue if needed.

**Closed as completed by rawmind0** 2020-08-05 17:37 UTC
